### ISSUE TITLE
Example request: Nesting validators

### ISSUE THREAD

**Issue by survivorm** [guyskk/validr#20]
Is there a way to create custom validator with the ability to use nested other validators (as list and dict do?)
I know i'm using the validr in an unexpected way, but the case is: I have the db results which i want to pack into arbitrary data structure. One of the fields of the list of nested dicts (representing db rows) is bytea in postgre (python bytes), packed json dump -> str -> bytes. So, i need to unpack it, and ideally - check the result as a dict.
Is it possible?

**Comment by guyskk** [comment]
`T.list( T.dict )` accept list of arbitrary dict, is it meet your requirements?

**Comment by survivorm** [comment]
I mean like:
```python 
plain_rule_schema_out = T.dict(
    id=T.int,
    enabled=T.bool.optional.default,
    ttl=T.int.optional,
    settings=T.bytearrjson(
      T.dict(
        addr=T.netaddr
      )
    )
)
```

**Comment by guyskk** [comment]
Not possible. I think it's better to decode bytearrjson then feed to validr, custom validator is over used.

**Comment by survivorm** [comment]
Ok, thanks for the reply
